FORMAT: 1A
HOST: http://api.gizwits.com

# Gizwits Open API

## Error codes

| status |     code     | message |
|--------|:------------:|--------:|
| 200    | 9000         | OK      |
| 400    | 9001         | mac already registered!      |
| 400    | 9002         | product_key invalid      |
| 400    | 9003         | appid invalid      |
| 400    | 9004         | token invalid      |
| 400    | 9005         | user not exist      |
| 400    | 9006         | token expired      |
| 400    | 9007         | m2m_id invalid      |

## Error Message

    {
      "error_code": "9002",
      "error_message": "xxx"
    }

# Group API for apps

## Users [/app/users]
### Create User [POST]

**Notice:** this API should go via https.

Both anonymous user register & login should call this API.

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            
    + Body
            
            {
                "phone_id": "adkaldk"
            }

+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }
            
+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
    
            {
                "username": "bob",
                "password": "123456"
            }
            
+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }
            
+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
 
            {   
                "authData": {
                    "src": "baidu|sina|qq",
                    "uid": "2346677",
                    "token":"pnktnjyb996sj4p156gjtp4im"
                }
            }
            
+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }

## User Detail [/users/{uid}]

### Update User Info [PUT]

Anonymous user PUT username & password to become a normal user.


+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "username": "bob",
                "password": "abda2"
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }


+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
    
    + Body
    
            {
                "old_pwd": "123456",
                "new_pwd": "123456"
            }
            
+ Response 200 (application/json)

    + Body
    
            { 
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "email": "bob@bob.com",
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "phone": "1328830223",
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }


## Login [/login]

### Login [POST]

**Notice:** this API should go via https.

username can be username or email or phone.


+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
    
            {
                "username": "bob",
                "password": "123456"
            }
            
+ Response 200 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }

## Get Codes [/codes]

### Get Codes [POST]

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "phone": "13223233"
            }

+ Response 200 (application/json)


## Request Password Reset [/requestPasswordReset]

### Request Password Reset [POST]

Can reset password for user who has email or phone.

If reset password by phone, should call get codes API first.


+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "email": "bob@bob.com"
            }

+ Response 200 (application/json)

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "phone": "13232433",
                "code": "13232',
                "new_pwd": "1323200"
            }

+ Response 200 (application/json)


## Device history data [/devdata/{did}{?start_ts}{&end_ts}{&limit}{&skip}]

History data is ordered by ts descending.

+ Parameters
    + did (required, string, `abcada`)
    + start_ts (required, number, `1349032093`)
    + end_ts (required, number, `1349032093`)
    + limit (optional, number, `20`)
    + skip (optional, number, `0`)

### Retrieve device history data [GET]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

+ Response 200 (application/json)

    + Body

            {
                "data": [{
                    "ts": 148293984328,
                    "payload": "123456"
                },{
                    "ts": 148293984328,
                    "payload": "123456"
                }]
            }


## Bindings [/app/bindings?{limit}&{skip}]

### Get Bound Devices [GET]

M2M will also call this API to get user bindings.

* Parameters
    + limit (optional, number, `20`)
    + skip (optional, number, `0`)

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
+ Response 201 (application/json)

    + Body
    
            {
                "devices": [{
                    "product_key": "akdlfkad",
                    "did": "abcada",
                    "mac": "1122334455667788",
                    "passcode": "123456",
                    "host": "m2m.gizwits.com",
                    "port": "3128"
                },{
                    "product_key": "akdlfkad",
                    "did": "abcada",
                    "mac": "1122334455667788",
                    "passcode": "123456",
                    "host": "m2m.gizwits.com",
                    "port": "3128"
                }]
            }

### Bind Devices [POST]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
    + Body
    
            {
                "devices": [{
                    "did": "abcada",
                    "passcode": "123456"
                },{
                    "did": "abcada",
                    "passcode": "123456"
                }]
            }
    
+ Response 200 (application/json)

           {
                "success": ['abc', 'add'],
                "failed": ['adad', 'ee']
           }

### Unbind Devices [DELETE]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
    + Body
    
            {
                "devices": [{
                    "did": "abcada",
                    "passcode": "123456"
                },{
                    "did": "abcada",
                    "passcode": "123456"
                }]
            }
    
+ Response 200 (application/json)


## Device Detail [/devices/{did}]
    
### Get Device Info [GET]

+ Parameters
    + did (required, string, `abcada`)

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
+ Response 200 (application/json)

    + Body
    
            {
                "did": "abcada",
                "mac": "1122334455667788",
                "passcode": "123456",
                "host": "m2m.gizwits.com",
                "port": "3128"
            }


# Group API for devices

## Devices [/dev/devices]

### Create Device [POST]

+ Request (application/x-www-form-urlencoded)

    + Body
        
            product_key=abcadfe&passcode=adjfakdk&mac=112233445566

            
+ Response 201 (application/text)

    + Body
    
            did=abaadd


## Device Provision [/dev/devices/{did}]

+ Parameters
    + did (required, string, `adaad`)

### Device Provision [GET]

+ Request (application/text)

+ Response 200 (application/text)

    + Body
    
            host=m2m.gizwits.com&port=3128&server_ts=1283200300

            
## OTA [/ota/{did}]

+ Parameters
    + did (required, string, `abcada`)

### Check OTA [GET]

+ Request (application/text)

+ Response 200 (application/text)

            
+ Request (application/text)

+ Response 200 (application/text)

    + Body
    
            ver=2&url=http://xxx


# Group API for M2M

## Verify User [/verify/user]

### Verify User [POST]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "uid": "akkdlfeiow", 
                "token": "akdlfkad"
            }
            
+ Response 401 (application/json)

+ Request (application/json)

    + Header
    
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "uid": "akkdlfeiow", 
                "token": "akdlfkad"
            }
            
+ Response 200 (application/json)

## Verify Device [/verify/device]

### Verify Device [POST]

+ Request (application/json)

    + Header
    
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "did": "akkdlfeiow", 
                "passcode": "akdlfkad"
            }
            
+ Response 401 (application/json)

+ Request (application/json)

    + Header
    
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "did": "akkdlfeiow", 
                "passcode": "akdlfkad"
            }
            
+ Response 200 (application/json)

    + Body

            {
                "mac": "adkflald",
                "product_key": "akdlfkad"
            }
