FORMAT: 1A
HOST: http://api.gizwits.com

# Gizwits Open API

## Error codes

| status |     code     | message |
|--------|:------------:|--------:|
| 400    | 9001         | mac already registered!      |
| 400    | 9002         | product_key invalid      |
| 400    | 9003         | appid invalid      |
| 400    | 9004         | token invalid      |
| 400    | 9005         | user not exist      |
| 400    | 9006         | token expired      |
| 400    | 9007         | m2m_id invalid      |
| 500    | 9008         | server error      |
| 400    | 9009         | code expired      |
| 400    | 9010         | code invalid      |
| 400    | 9011         | sandbox scale quota exhausted!      |
| 400    | 9012         | production scale quota exhausted!      |
| 400    | 9013         | product has no request scale!      |
| 400    | 9014         | device not found!      |
| 400    | 9015         | form invalid!      |
| 400    | 9016         | did or passcode invalid!      |
| 401    | 9017         | device not bound!      |
| 400    | 9018         | phone unavailable!      |
| 400    | 9019         | username unavailable!      |
| 400    | 9020         | username or password error!      |
| xxx    | 9999         | reserved      |

## Error Message

    {
      "error_code": "9002",
      "error_message": "xxx"
    }

# Group API for apps

## Users [/app/users]

### Create User [POST]

**Notice:** this API should go via https.

Both anonymous user register & login should call this API.

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            
    + Body
            
            {
                "phone_id": "apiary"
            }

+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }
            
+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
    
            {
                "username": "bob",
                "password": "123456"
            }
            
+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
    
            {
                "phone": "123456",
                "password": "123456",
                "code": "abc"
            }
            
+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }

            
+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
 
            {   
                "authData": {
                    "src": "baidu|sina|qq",
                    "uid": "2346677",
                    "token":"pnktnjyb996sj4p156gjtp4im"
                }
            }
            
+ Response 201 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }

### Update User Info [PUT]

Anonymous user PUT username & password to become a normal user.

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "username": "bob",
                "password": "abda2"
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }


+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
    
    + Body
    
            {
                "old_pwd": "123456",
                "new_pwd": "123456"
            }
            
+ Response 200 (application/json)

    + Body
    
            { 
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "email": "bob@bob.com",
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "phone": "1328830223",
                "code": "abc"
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body

            {
                "phone": "1328830223",
                "password": "123456",
                "code": "123"
            }

+ Response 200 (application/json)

    + Body

            {
                "updatedAt": "2011-11-07T21:25:10.623Z"
            }


## Login [/app/login]

### Login [POST]

**Notice:** this API should go via https.

username can be username or email or phone.


+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
    
    + Body
    
            {
                "username": "bob",
                "password": "123456"
            }
            
+ Response 200 (application/json)

    + Body
    
            { 
                "uid": "akkdlfeiow", 
                "token": "akdlfkad",
                "expire_at": 13894002020
            }

## Get & Verify Codes [/app/codes]

### Get & Verify Codes [POST]

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "phone": "13223233"
            }

+ Response 200 (application/json)

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "phone": "13223233",
                "code": "123456"
            }

+ Response 200 (application/json)


## Request Password Reset [/app/reset_password]

### Request Password Reset [POST]

Can reset password for user who has email or phone.

If reset password by phone, should call get codes API first.


+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "email": "bob@bob.com"
            }

+ Response 200 (application/json)

+ Request (application/json)

    + Header

            X-Gizwits-Application-Id: {appid}

    + Body

            {
                "phone": "13232433",
                "code": "13232',
                "new_pwd": "1323200"
            }

+ Response 200 (application/json)


## Device history data [/app/devdata/{did}{?start_ts,end_ts,entity,attr,limit,skip}]

History data is ordered by ts descending.

+ Parameters
    + did (required, string, `gdGn7PzAYf4VrhnVag5x8D`)
    + start_ts (optional, number, `1349032093`)
    + end_ts (optional, number, `1349032093`)
    + entity (optional, number, `1`)
    + attr (optional, number, `6`)
    + limit (optional, number, `20`)
    + skip (optional, number, `0`)

### Retrieve device history data [GET]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

+ Response 200 (application/json)

    + Body

            {
                "data": [{
                    "ts": 148293984328,
                    "entity": 1,
                    "attr": 1,
                    "val": 10
                },{
                    "ts": 148293984328,
                    "entity": 1,
                    "attr": 1,
                    "val": 10
                }]
            }


## Bindings [/app/bindings{?limit,skip}]

### Get Bound Devices [GET]

M2M will also call this API to get user bindings.

* Parameters
    + limit (optional, number, `20`)
    + skip (optional, number, `0`)

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
+ Response 200 (application/json)

    + Body
    
            {
                "devices": [{
                    "product_key": "akdlfkad",
                    "did": "abcada",
                    "mac": "1122334455667788",
                    "is_online": false,
                    "passcode": "123456",
                    "host": "m2m.gizwits.com",
                    "port": 3128
                },{
                    "product_key": "akdlfkad",
                    "did": "abcada",
                    "mac": "1122334455667788",
                    "is_online": false,
                    "passcode": "123456",
                    "host": "m2m.gizwits.com",
                    "port": 3128
                }]
            }

### Bind Devices [POST]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
    + Body
    
            {
                "devices": [{
                    "did": "gdGn7PzAYf4VrhnVag5x8D",
                    "passcode": "gokit"
                }]
            }
    
+ Response 200 (application/json)

           {
                "success": ['abc', 'add'],
                "failed": ['adad', 'ee']
           }

### Unbind Devices [DELETE]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
    + Body
    
            {
                "devices": [{
                    "did": "gdGn7PzAYf4VrhnVag5x8D",
                    "passcode": "gokit"
                }]
            }
    
+ Response 200 (application/json)

           {
                "success": ['abc', 'add'],
                "failed": ['adad', 'ee']
           }


## Device Detail [/app/devices/{did}]
    
### Get Device Info [GET]

+ Parameters
    + did (required, string, `abcada`)

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}
            
+ Response 200 (application/json)

    + Body
    
            {
                "product_key": "akdlfkad",
                "did": "abcada",
                "mac": "1122334455667788",
                "is_online": false,
                "passcode": "123456",
                "host": "m2m.gizwits.com",
                "port": "3128"
            }

## Query Device [/app/devices{?product_key,mac}]

### Query Device [GET]

+ Parameters
    + product_key (required, string, `product_key`)
    + mac (required, string, `112233445566`)

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            
+ Response 200 (application/json)

    + Body
    
            {
                "did": "abcada",
                "passcode": "123456",
            }


## Control Device [/app/control/{did}]

### Remote Control Device [POST]

+ Parameters
    + did (required, string, `did`)

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-User-token: {token}

    + Body
    
            {
                "raw": [<byte>, <byte>, ...]
            }
            
+ Response 200 (application/json)

    + Body
    
            {}


# Group API for devices

## Devices [/dev/devices]

### Create Device [POST]

#### Errors

| status |     code     | message |
|--------|:------------:|--------:|
| 400    | 9002         | product_key invalid      |

+ Request (application/x-www-form-urlencoded)

    + Body
        
            product_key=d69af59e38c711e4a29d52540052876d&passcode=gokit&mac=112233445566

            
+ Response 201 (application/text)

    + Body
    
            did=gdGn7PzAYf4VrhnVag5x8D


## Device Provision [/dev/devices/{did}]

+ Parameters
    + did (required, string, `adaad`)

### Device Provision [GET]

+ Request (application/text)

+ Response 200 (application/text)

    + Body
    
            host=m2m.gizwits.com&port=3128&server_ts=1283200300

            
## OTA - Get Target fid [/dev/ota/target_fid{?did,product_key,type,hard_version,soft_version,current_fid}]

+ Parameters
    + did (required, string, `abcada`)
    + product_key (required, string, `pk`)
    + type (required, int, `1`) ... wifi is 1, and mcu is 2
    + hard_version (required, string, `hv`)
    + soft_version (required, string, `sv`)
    + current_fid (required, int, `fid`)

### Get target fid [GET]

+ Request (application/text)

+ Response 200 (application/text)

    + Body
    
            target_fid=2&download_url=http://xxx


## OTA - Download Firmware [/dev/ota/download{?product_key,type,hard_version,soft_version,fid}]

+ Parameters
    + product_key (required, string, `pk`)
    + type (required, int, `1`) ... wifi is 1, and mcu is 2
    + hard_version (required, string, `hv`)
    + soft_version (required, string, `sv`)
    + fid (required, int, `fid`)

### Download Firmware [GET]

+ Request (application/text)

+ Response 200 (application/text)

    + Header

            Content-Type: application/octet-stream
            Content-Disposition: attachment; filename=xxxx.bin

    + Body

            file


# Group API for M2M

## Verify User [/m2m/verify/user]

### Verify User [POST]

+ Request (application/json)

    + Header
    
            X-Gizwits-Application-Id: {appid}
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "uid": "akkdlfeiow", 
                "token": "akdlfkad"
            }
            
+ Response 401 (application/json)

+ Request (application/json)

    + Header
    
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "uid": "akkdlfeiow", 
                "token": "akdlfkad"
            }
            
+ Response 200 (application/json)

## Verify Device [/m2m/verify/device]

### Verify Device [POST]

+ Request (application/json)

    + Header
    
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "did": "gdGn7PzAYf4VrhnVag5x8D", 
                "passcode": "gokit",
                "xpasscode": "akdlfkad"
            }
            
+ Response 401 (application/json)

+ Request (application/json)

    + Header
    
            X-Gizwits-M2M-Id: {m2m_id}

    + Body
    
            {
                "did": "gdGn7PzAYf4VrhnVag5x8D", 
                "passcode": "gokit",
                "xpasscode": "akdlfkad"
            }
            
+ Response 200 (application/json)

    + Body

            {
                "mac": "adkflald",
                "product_key": "akdlfkad"
            }
